#ifndef TGSTKBRAINTISSUETYPE_H
#define TGSTKBRAINTISSUETYPE_H

enum tgstkBrainTissueType : unsigned short {

    BACKGROUND=0,
    NECROTIC_CORE=1,
    CSF=2,
    GREY_MATTER=3,
    WHITE_MATTER=4,
    OEDEMA=5,
    ENHANCING_CORE=6
};

#endif // TGSTKBRAINTISSUETYPE_H
